name: Deploy Site to Pages

on:
  push:
    paths-ignore: ["LICENSE", "README.md"]
    branches: [main]
  workflow_dispatch:
    inputs:
      hugoVersion:
        description: "Hugo Version (optional)"
        required: false
        default: "0.122.0"

concurrency: { group: pages, cancel-in-progress: true }

defaults: { run: { shell: bash } }

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env: { HUGO_VERSION: "0.122.0" }

    steps:
      # 1) Hugo 설치
      - name: Install Hugo ${{ env.HUGO_VERSION }}
        run: |
          wget -O ${{ runner.temp }}/hugo.deb \
            https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb &&
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # 2) 코드 체크아웃 (v4)
      - uses: actions/checkout@v4

      # 3) Pages 메타데이터 로드 (v3 최신)
      - id: pages
        uses: actions/configure-pages@v3

      # 4) (옵션) 서브모듈 초기화
      - run: git submodule update --init --recursive

      # 5) Hugo 빌드
      - run: hugo --verbose --baseURL "${{ steps.pages.outputs.base_url }}"

      # 6) 빌드 결과 업로드 (v3 → 내부에서 upload-artifact v4 사용)
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./public }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 7) GitHub Pages에 배포 (v4 최신)
      - id: deployment
        uses: actions/deploy-pages@v4
